dbHost: "localhost"
dbPort: 5432
dbUser: "postgres"
dbPassword: "postgres"
dbDatabase: "postgres"
rpcUrl: "http://127.0.0.1:8545"
logLevel: "info"
syncInterval: 10
indexInterval: 10
port: 8080
marketAddress: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
wssUrl: "ws://127.0.0.1:8545"